### PR TITLE
Add JavaScript to add referrer to link back to Kickstarter

### PR DESCRIPTION
**Pull request by cantino**
@benlachman @rickychilcott This PR adds URL params from the referrer to the buying-guide to the outbound link back to Kickstarter. This should preserve UTM params, but *it will only work if we move to https, as referrer is not sent from https -> http.* Can we move meetglow.com to https?

### CODE REVIEW

**Comment by rickychilcott** [comment]
@benlachman this is hosted on Github Pages, correct? There isn't a way to have Github pages provide SSL for a custom domain directly, however this can be done with Cloudflare: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc


Alternatively, we could use nginx as a proxy to front the service (which is effectively what Cloudflare is doing), but would take either spinning up a separate box or putting it on `demo` or something. Cloudflare would be my recommendation.

**Comment by benlachman** [comment]
Yeah. Cloudflare doesn't do truly secure HTTPS since the cloudflare to GitHub hop isn't secure. But probably the easiest way to get this.

**Comment by rickychilcott** [comment]
Do we care if it's truly secure? No sensitive data is passing here. That said, github pages cal seve SSL over the github.io domain so it definitely can be done fully securely.

Ricky
Rakefire [https://www.rakefire.io/] (740) 561-1361
On Sat, Sep 2, 2017 at 4:53 PM, Ben Lachman <notifications@github.com> wrote:
Yeah. Cloudflare doesn't do truly secure HTTPS since the cloudflare to GitHub hop isn't secure. But probably the easiest way to get this.

**Comment by cantino** [comment]
Agreed, we're only using SSL so JS will send the headers; no actual data needs to be secured as far as I know.

**Pull request merged**
