### PR TITLE
Merge referrer tracking

### PR DESCRIPTION
**Pull request by benlachman**

### CODE REVIEW

**Comment by benlachman** [comment]
@cantino Merged and fronted with HTTPS CloudFlare. Can you test to make sure it's doing what you planned?

**Comment by cantino** [comment]
@benlachman, make sure all links on the Kickstarter page are to the https link for the buying guide. It won't work right now, as they're https.

**Comment by cantino** [comment]
Also, make sure the link is to https://meetglow.com/buying-guide/ (with the trailing `/`). Without it, I'm seeing a redirect from https://meetglow.com/buying-guide to http://meetglow.com/buying-guide/ to https://meetglow.com/buying-guide/, which has an http only phase in the middle and loses the referrer.

**Comment by benlachman** [comment]
Okay. Give it a try now.

->Ben

**Pull request merged**
